baseURL: "https://strayturtle.github.io/portfolio/"
title: "Portfolio - Stray Turtle"
languageCode: "ja"
hasCJKLanguage: true
relativeURLs: true
disableKinds: ["page", "section", "taxonomy", "term", "RSS"]

outputs:
  home: ["HTML"]
