languageCode = "ja"
hasCJKLanguage = true
baseurl = "https://www.strayturtle.dev/"
title = "Portfolio - Stray Turtle"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS"]
googleAnalytics = "UA-161504385-2"

[params]
  description = "主にプロフィールとWeb制作のスキルを紹介するポートフォリオです。AMP Storiesで制作しました。"
  images = ["logo.png"]
  faviocn = ""

[params.author]
  name = "Stray Turtle"
  location = "Kyoto, Japan"
  email = "https://forms.gle/6Rb9NHgWFd9VGiJF9"

[[params.projects]]
  name = "Portfolio"
  url = "https://www.strayturtle.dev/"
  image = "https://blog.strayturtle.dev/apple-touch-icon.png"
  description = ""
  usedSkills = ["HTML5", "CSS", "AMP Stories", "Hugo"]

[[params.projects]]
  name = "Blog"
  url = "https://blog.strayturtle.dev/"
  image = "https://blog.strayturtle.dev/apple-touch-icon.png"
  description = ""
  usedSkills = ["HTML5", "CSS", "AMP", "Hugo"]

[[params.contact]]
  name = "Twitter"
  url = "https://twitter.com/strayturtle13"

[[params.contact]]
  name = "GitHub"
  url = "https://github.com/strayturtle"

[outputFormats.Bookend]
  baseName = "bookend"
  isPlainText = true
  mediaType = "application/json"

[outputs]
  home = ["HTML", "RSS", "Bookend"]
