languageCode = "ja"
hasCJKLanguage = true
baseurl = "https://strayturtle.github.io/portfolio/"
title = "Portfolio - Stray Turtle"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS"]
googleAnalytics = "UA-161504385-2"

[params]
  description = "主にプロフィールとWeb制作のスキルを紹介するポートフォリオです。Web Storiesで制作しました。"
  images = ["logo.png"]
  faviocn = ""

[params.author]
  name = "Stray Turtle"
  location = "Kyoto, Japan"
  email = "https://forms.gle/6Rb9NHgWFd9VGiJF9"

[[params.skills]]
  name = "HTML5"
  rating = 5

[[params.skills]]
  name = "CSS3"
  rating = 4.5

[[params.skills]]
  name = "JavaScript"
  rating = 3

[[params.skills]]
  name = "Hugo"
  rating = 4

[[params.skills]]
  name = "PHP"
  rating = 1.5

# [[params.projects]]
#   name = "Portfolio"
#   url = "https://www.strayturtle.dev/"
#   image = ""
#   description = "このサイトです。"
#   usedSkills = ["HTML5", "CSS3", "Web Stories", "Hugo"]

[[params.projects]]
  name = "Blog"
  url = "https://blog.strayturtle.dev/"
  image = "https://blog.strayturtle.dev/apple-touch-icon.png"
  description = "Web系の技術記事を公開しています。"
  usedSkills = ["HTML5", "CSS3", "AMP", "Hugo"]

[[params.contact]]
  name = "Twitter"
  url = "https://twitter.com/strayturtle13"

[[params.contact]]
  name = "GitHub"
  url = "https://github.com/strayturtle"

[outputFormats.Bookend]
  baseName = "bookend"
  isPlainText = true
  mediaType = "application/json"

[outputs]
  home = ["HTML", "RSS", "Bookend"]
