languageCode = "ja"
hasCJKLanguage = true
baseurl = "https://strayturtle.github.io/portfolio/"
title = "Portfolio - Stray Turtle"
disableKinds = ["page", "section", "taxonomy", "term", "RSS"]
googleAnalytics = "UA-161504385-2"

[params]
description = "主にプロフィールとWeb制作のスキルを紹介するポートフォリオです。Web Storiesで制作しました。"
datePublished = "2020-03-14T12:00:00+09:00"
images = ["logo.png"]
faviocn = ""

[params.author]
name = "Stray Turtle"
location = "Japan"
email = "https://forms.gle/6Rb9NHgWFd9VGiJF9"

[[params.skills]]
name = "HTML5"
rating = 5

[[params.skills]]
name = "CSS3"
rating = 4.5

[[params.skills]]
name = "JavaScript"
rating = 3

[[params.skills]]
name = "Hugo"
rating = 4

[[params.skills]]
name = "PHP"
rating = 1.5

[[params.projects]]
name = "Portfolio"
url = "https://strayturtle.github.io/portfolio/"
image = ""
description = "このサイトです。"
usedSkills = ["HTML5", "CSS3", "Web Stories", "Hugo"]

[[params.contact]]
name = "Twitter"
url = "https://twitter.com/strayturtle13"

[[params.contact]]
name = "GitHub"
url = "https://github.com/strayturtle"

[outputs]
home = ["HTML"]
