name: Build and Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.76.3"
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir
        env:
          TZ: "Asia/Tokyo"

      - name: Save public dir
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load public dir
        uses: actions/download-artifact@v1
        with:
          name: public

      - name: Deploy to hosting
        uses: peaceiris/actions-gh-pages@v3
        env:
          TZ: "Asia/Tokyo"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
